pipeline {
    agent any

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Nodstan/Calculator.git'
            }
        }

        stage('Compile') {
            steps {
                bat 'mvn clean compile'
            }
        }

        stage('Unit test') {
            steps {
                bat 'mvn test'
            }
        }

        stage('Static Code Analysis') {
            steps {
                // Run Checkstyle validation
                bat 'mvn checkstyle:check'

                // Generate HTML report
                bat 'mvn checkstyle:checkstyle'

                // Publish Checkstyle report to Jenkins UI
                publishHTML(target: [
                reportDir: 'target/site',       // Maven default Checkstyle HTML location
                reportFiles: 'checkstyle.html', // HTML report generated by Maven
                reportName: "Checkstyle Report"
                ])
            }
        }

        stage('Code coverage') {
            steps {
                bat 'mvn jacoco:report'

                publishHTML(target: [
                    reportDir: 'target/site/jacoco',
                    reportFiles: 'index.html',
                    reportName: 'JaCoCo Report'
                ])

                bat 'mvn jacoco:check'
            }
        }
    }
}
